### ISSUE TITLE
Syntax formatting does not allow for nested optionals

### ISSUE THREAD

**Issue by itamarhaber** [redis/redis-io#159]
This blocks https://github.com/antirez/redis-doc/issues/1007 and https://github.com/antirez/redis-doc/issues/1008

**Comment by itamarhaber** [comment]
Also related to https://github.com/antirez/redis-doc/pull/1284

**Comment by wingunder** [comment]
Hi @itamarhaber,
re: https://github.com/redis/redis-doc/pull/1400#issuecomment-700047516
"Syntax formatting does not allow for nested optionals" is exactly what is missing in order to add the missing MAXLEN of XADD. 
Could you please point me to the software that parses command.json. I think this needs to be adapted in order to support "nested optionals". It would also be nice if the parsing of the commands.json file could be targeted in the makefile (for testing purposes).
